version: '3.7'

services:
  api:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:api
    command: gunicorn app:app 0.0.0.0:80
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env

  # nginx:
  #   image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api
